title: "Affiliates"
email: wowthemesnet@gmail.com
timezone: UTC
# baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"

paginate: 30






# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives